- name: "Ensure cron daemon is enabled and running"
  systemd:
    name: crond
    state: started
    enabled: yes
  tags:
    - patch



- name: "Ensure permissions on /etc/crontab are configured"
  file:
      dest: /etc/crontab
      owner: root
      group: root
      mode: 0600
  tags:
      - patch
