- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
    name: net.ipv6.route.flush
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: restart sshd
  service:
      name: sshd
      state: restarted