rhel_warning_banner: |
    ################################# WARNING!!! #####################################
    #                                                                                #
    # You are accessing a TURAN CYBER HUB's information system. Unauthorized or      #
    # improper use of this system may result in disciplinary action, as well as      #
    # civil and criminal penalties. By using this information system, you understand #
    # and consent to the following:, (1) You have no reasonable expectation of       #
    # privacy regarding any communication or information transiting or stored on     #
    # this information system., (2) All attempts to access and use this system       #
    # and/or its resources are subject to monitoring and recording., (3) You         #
    # expressly consent to this monitoring or recording, and it is advised that if   #
    # such reveals evidence any criminal activity or abuse of authority, the         #
    # information will be reported to authorities for action.                        #
    #                                                                                #
    ##################################################################################

rhel_warning_motd: |
    Authorized uses only. All activity may be monitored and reported.
